import React, { createContext, useContext, useState, useCallback } from "react";

export type Lang = "en" | "zh";

const dict: Record<Lang, Record<string, string>> = {
  en: {
    // General
    tables: "Tables",
    floor: "Floor",
    menu: "Menu",
    orders: "Orders",
    settings: "Settings",
    search: "Search",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    back: "Back",
    close: "Close",
    all: "All",
    
    // Table statuses
    available: "Available",
    reserved: "Reserved",
    ordering: "Ordering",
    ordered: "Ordered",
    dirty: "Dirty",
    cleaning: "Cleaning",
    
    // Table actions
    transfer_table: "Transfer",
    merge_tables: "Merge",
    split_table: "Split",
    select_target: "Select target table",
    select_tables_to_merge: "Select tables to merge",
    split_into: "Split into",
    transfer_from: "Transfer from",
    merge_confirm: "Confirm Merge",
    cancel_action: "Cancel",
    
    // Zones
    main_hall: "Main Hall",
    patio: "Patio",
    private: "Private",
    bar: "Bar",
    
    // Menu
    search_table: "Search table...",
    search_menu: "Search menu...",
    popular: "Popular",
    combos: "Combos",
    starters: "Starters",
    mains: "Mains",
    noodles: "Noodles",
    rice: "Rice",
    sides: "Sides",
    desserts: "Desserts",
    beverages: "Beverages",
    alcohol: "Alcohol",
    combo: "COMBO",
    includes: "Includes",
    select: "Select",
    unavailable: "Unavailable",
    sold_out: "Sold out",
    add_to_order: "Add to Order",
    review_order: "Review Order",
    items: "items",
    
    // Modifiers
    spice_level: "Spice Level",
    required: "Required",
    select_one: "Select one",
    select_multiple: "Select multiple",
    special_notes: "Special Notes",
    notes_placeholder: "e.g. No onion, extra chilli...",
    
    // Order
    subtotal: "Subtotal",
    service_charge: "Service Charge",
    gst: "GST 9%",
    total: "Total",
    pay: "Pay",
    send_to_kitchen: "Send to Kitchen",
    serviceFlow: "Service Flow",
    serviceFlowDesc: "How orders are processed at POS terminals",
    restaurant: "Restaurant",
    fastFood: "Fast Food",
    restaurantDesc: "Order → Kitchen → Dine → Pay",
    fastFoodDesc: "Order → Pay → Kitchen → Pickup",
    orderSent: "Order Sent",
    awaitingPayment: "Awaiting Payment",

    // Service modes
    dine_in: "Dine-in",
    takeaway: "Takeaway",
    delivery: "Delivery",
    pickup: "Pickup",
    takeaway_order: "Takeaway Order",
    delivery_order: "Delivery Order",
    
    // Table info
    seats: "seats",
    guests: "guests",
    max_seats: "max",
    
    // Theme
    light: "Light",
    dark: "Dark",
    language: "Language",
    english: "English",
    chinese: "中文",
    
    // Admin
    dashboard: "Dashboard",
    staff: "Staff",
    crm: "CRM",
    kds_monitor: "KDS Monitor",
    sales_report: "Sales Report",
    finance: "Finance",
    
    // Flexible combo
    flexible_combo: "Flexible Set",
    choose_your: "Choose your",
    selected: "Selected",
    remaining: "remaining",

    // CheckPanel
    select_table_start: "Select a table to start",
    no_items: "No items yet",
    add_from_menu: "Add items from the menu",

    // Payment
    payment: "Payment",
    payment_complete: "Payment Complete",
    payment_method: "Payment Method",
    amount_due: "Amount Due",
    card: "Card",
    cash: "Cash",
    cash_received: "Cash Received",
    change: "Change",
    tap_insert_swipe: "Tap, insert, or swipe card",
    scan_qr: "Scan",
    processing: "Processing...",
    confirm_payment: "Confirm Payment",
    paid_via: "paid via",
    done: "Done",
    discount: "Discount",

    // History
    history: "History",
    order_history: "Order History",
    order_detail: "Order Detail",
    no_history: "No completed orders yet",
    cash_payment: "Cash Payment",
    net_paid: "Net Paid",
    all_methods: "All Methods",
    all_modes: "All Modes",
    promo: "Promo",
    member: "Member",
    split_bill: "Split",
    enter_promo_code: "Enter promo code...",
    apply: "Apply",
    invalid_promo: "Invalid promo code",
    remove: "Remove",
    member_discount_applied: "Member Discount",
    split_into_n: "Split into",
    each_pays: "Each pays",
    per_person: "Per person",
    promotions: "Promotions",
    add_new_member: "Add New Member",
    add_new: "Add New",
    top_up: "Top Up",
    balance: "Balance",
    phone_number: "Phone number",
    no_member_found: "No member found",
    link_member: "Link Member",
    search: "Search",
    name: "Name",
    enter_name: "Enter name",
    phone: "Phone",
    email: "Email",
    register_member: "Register Member",
    select_amount: "Select amount",
    custom_amount: "Custom amount",
    confirm_top_up: "Confirm Top Up",
    top_up_success: "Top Up Successful!",
    new_balance: "New balance",
    done: "Done",
    enter_pin: "Enter PIN",
    wrong_pin: "Wrong PIN, try again",
    top_up_amount: "Top Up Amount",
    use_balance: "Use Balance",
    use_points: "Use Points",
    available_balance: "Available balance",
    available_points: "Available points",
    use_all: "Use All",
    apply_balance: "Apply Balance",
    balance_credit: "Balance Credit",
    convert_points: "Convert points to balance",
    convert_to_balance: "Convert to Balance",
    points_converted: "Points Converted!",
    added_to_balance: "added to balance",
    use_balance_now: "Use Balance Now",
    all: "All",
    // Kiosk & QR
    kiosk: "Kiosk",
    qr_order: "QR Order",
    start_order: "Start Order",
    collection_number: "Collection Number",
    your_order: "Your Order",
    view_cart: "View Cart",
    proceed_to_pay: "Proceed to Pay",
    add_to_cart: "Add to Cart",
    new_order: "New Order",
    confirm_table: "Confirm Table",
    member_login: "Member Login",
    continue_as_guest: "Continue as Guest",
    login_with_phone: "Login with Phone",
    send_otp: "Send OTP",
    verify: "Verify",
    register_continue: "Register & Continue",
    pay_now: "Pay Now",
    pay_at_counter: "Pay at Counter Later",
    order_submitted: "Order Submitted",
    pay_later_note: "Please pay at the counter when ready",

    // Reservations
    reserveTable: "Reserve Table",
    cancelReservation: "Cancel Reservation",
    seatGuests: "Seat Guests",
    guestName: "Guest Name",
    guestCount: "Guest Count",
    phone: "Phone",
    reservationType: "Reservation Type",
    instantHold: "Now",
    scheduled: "Scheduled",
    selectDate: "Select Date",
    selectTime: "Select Time",
    notes: "Notes",
    cancelReason: "Cancel Reason",
    customerCancelled: "Customer Cancelled",
    noShow: "No-Show",
    otherReason: "Other",
    cancelNote: "Note",
    confirmCancel: "Confirm Cancel",
    actualGuestCount: "Actual Guest Count",
    searchMember: "Search member by phone",
    linkMember: "Link Member",
    skipMember: "Skip",
    seatAndOrder: "Seat & Order",
    reservationList: "Reservations",
    allReservations: "All",
    pendingReservations: "Pending",
    seatedReservations: "Seated",
    cancelledReservations: "Cancelled",
    noReservationsToday: "No reservations today",
    reservedAt: "Reserved at",
    reservedFor: "Reserved for",
    guestNameRequired: "Guest name is required",
    reservationInfo: "Reservation Info",
    memberTier: "Member Tier",
    noMemberFound: "No member found",

    // Menu management
    addCategory: "Add Category",
    editCategory: "Edit Category",
    deleteCategory: "Delete Category",
    categoryName: "Category Name",
    systemCategory: "System",
    uploadImage: "Upload Image",
    imageUrl: "Image URL",
    removeImage: "Remove",
    modifierGroups: "Modifier Groups",
    addModifierGroup: "Add Group",
    editModifierGroup: "Edit Group",
    deleteModifierGroup: "Delete Group",
    optionName: "Option Name",
    optionPrice: "Price",
    addOption: "Add Option",
    editItem: "Edit Item",
    itemDetails: "Item Details",
    comboConfig: "Combo Configuration",
    // Recipe
    ingredients: "Ingredients",
    addIngredient: "Add Ingredient",
    selectIngredient: "Select ingredient",
    quantityPerServing: "Qty per serving",
    estimatedCost: "Estimated Cost",
    linkedItems: "Linked Items",
    availablePortions: "Available Portions",
    projectedUsage: "Projected Usage",
    // Inventory intake
    receivingForm: "Receiving Form",
    scanInvoice: "Scan Invoice",
    analyzing: "Analyzing...",
    addRow: "Add Row",
    supplier: "Supplier",
    totalCost: "Total Cost",
    submitReceiving: "Submit Receiving",
    scanResult: "Scan Result",
    confidence: "Confidence",
    matchedItem: "Matched Item",
    reviewAndSubmit: "Review & Submit",
    noMatch: "No match",
    unitCost: "Unit Cost",
    // KDS
    kitchenDisplay: "Kitchen Display",
    kitchenView: "Kitchen",
    pickupView: "Pickup",
    startPreparing: "Start",
    markReady: "Ready",
    markServed: "Served",
    pickedUp: "Picked Up",
    orderCancelled: "ORDER CANCELLED",
    acknowledged: "Acknowledged",
    kdsWarningMinutes: "Warning Threshold (min)",
    kdsUrgentMinutes: "Urgent Threshold (min)",
    kdsTimingSettings: "KDS Timing",
    kdsTimingDesc: "Color coding thresholds for kitchen tickets",
    preparing: "Preparing",
    readyForPickup: "Ready for Pickup",
    newOrders: "New Orders",
  },
  zh: {
    tables: "桌位",
    floor: "楼层",
    menu: "菜单",
    orders: "订单",
    settings: "设置",
    search: "搜索",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    delete: "删除",
    back: "返回",
    close: "关闭",
    all: "全部",
    
    available: "空桌",
    reserved: "已预定",
    ordering: "点餐中",
    ordered: "已下单",
    dirty: "待清理",
    cleaning: "清理中",
    
    transfer_table: "换桌",
    merge_tables: "并桌",
    split_table: "拆桌",
    select_target: "选择目标桌位",
    select_tables_to_merge: "选择要合并的桌位",
    split_into: "拆分为",
    transfer_from: "从",
    merge_confirm: "确认合并",
    cancel_action: "取消",
    
    main_hall: "大厅",
    patio: "露台",
    private: "包厢",
    bar: "吧台",
    
    search_table: "搜索桌号...",
    search_menu: "搜索菜品...",
    popular: "热门",
    combos: "套餐",
    starters: "前菜",
    mains: "主菜",
    noodles: "面食",
    rice: "饭类",
    sides: "配菜",
    desserts: "甜品",
    beverages: "饮料",
    alcohol: "酒类",
    combo: "套餐",
    includes: "包含",
    select: "选择",
    unavailable: "暂不供应",
    sold_out: "已售罄",
    add_to_order: "加入订单",
    review_order: "查看订单",
    items: "件",
    
    spice_level: "辣度",
    required: "必选",
    select_one: "单选",
    select_multiple: "多选",
    special_notes: "特别备注",
    notes_placeholder: "例：不要洋葱，多加辣椒...",
    
    subtotal: "小计",
    service_charge: "服务费",
    gst: "消费税 9%",
    total: "合计",
    pay: "结账",
    send_to_kitchen: "下单",
    serviceFlow: "服务流程",
    serviceFlowDesc: "POS 终端的订单处理方式",
    restaurant: "餐厅模式",
    fastFood: "快餐模式",
    restaurantDesc: "点单 → 出餐 → 用餐 → 付款",
    fastFoodDesc: "点单 → 付款 → 出餐 → 取餐",
    orderSent: "已下单",
    awaitingPayment: "等待付款",

    dine_in: "堂食",
    takeaway: "外带",
    delivery: "外卖",
    pickup: "自取",
    takeaway_order: "外带订单",
    delivery_order: "外卖订单",
    
    seats: "座",
    guests: "位客人",
    max_seats: "最多",
    
    light: "浅色",
    dark: "深色",
    language: "语言",
    english: "English",
    chinese: "中文",
    
    dashboard: "仪表盘",
    staff: "员工",
    crm: "客户管理",
    kds_monitor: "出菜监控",
    sales_report: "销售报表",
    finance: "财务",
    
    flexible_combo: "自选套餐",
    choose_your: "选择你的",
    selected: "已选",
    remaining: "待选",

    select_table_start: "选择桌位开始",
    no_items: "暂无菜品",
    add_from_menu: "从菜单添加菜品",

    payment: "支付",
    payment_complete: "支付成功",
    payment_method: "支付方式",
    amount_due: "应付金额",
    card: "银行卡",
    cash: "现金",
    cash_received: "收到现金",
    change: "找零",
    tap_insert_swipe: "请刷卡、插卡或感应",
    scan_qr: "扫码",
    processing: "处理中...",
    confirm_payment: "确认支付",
    paid_via: "通过",
    done: "完成",
    discount: "折扣",

    history: "历史",
    order_history: "交易历史",
    order_detail: "交易详情",
    no_history: "暂无已完成订单",
    cash_payment: "现金支付",
    net_paid: "实收金额",
    all_methods: "全部方式",
    all_modes: "全部模式",
    promo: "优惠",
    member: "会员",
    split_bill: "拆分",
    enter_promo_code: "输入优惠码...",
    apply: "应用",
    invalid_promo: "无效优惠码",
    remove: "移除",
    member_discount_applied: "会员折扣",
    split_into_n: "拆分为",
    each_pays: "每人支付",
    per_person: "人均",
    promotions: "营销活动",
    add_new_member: "新增会员",
    add_new: "新增",
    top_up: "充值",
    balance: "余额",
    phone_number: "手机号码",
    no_member_found: "未找到会员",
    link_member: "关联会员",
    search: "搜索",
    name: "姓名",
    enter_name: "输入姓名",
    phone: "电话",
    email: "邮箱",
    register_member: "注册会员",
    select_amount: "选择金额",
    custom_amount: "自定义金额",
    confirm_top_up: "确认充值",
    top_up_success: "充值成功！",
    new_balance: "新余额",
    done: "完成",
    enter_pin: "输入密码",
    wrong_pin: "密码错误，请重试",
    top_up_amount: "充值金额",
    use_balance: "使用余额",
    use_points: "使用积分",
    available_balance: "可用余额",
    available_points: "可用积分",
    use_all: "全部使用",
    apply_balance: "应用余额",
    balance_credit: "余额抵扣",
    convert_points: "积分转余额",
    convert_to_balance: "转为余额",
    points_converted: "积分已转换！",
    added_to_balance: "已添加到余额",
    use_balance_now: "立即使用余额",
    all: "全部",
    // Kiosk & QR
    kiosk: "自助点餐",
    qr_order: "扫码点餐",
    start_order: "开始点餐",
    collection_number: "取餐号",
    your_order: "您的订单",
    view_cart: "查看购物车",
    proceed_to_pay: "去支付",
    add_to_cart: "加入购物车",
    new_order: "新订单",
    confirm_table: "确认桌号",
    member_login: "会员登录",
    continue_as_guest: "以访客身份继续",
    login_with_phone: "手机号登录",
    send_otp: "发送验证码",
    verify: "验证",
    register_continue: "注册并继续",
    pay_now: "立即支付",
    pay_at_counter: "稍后柜台支付",
    order_submitted: "订单已提交",
    pay_later_note: "请稍后到柜台支付",

    // Reservations
    reserveTable: "预订桌位",
    cancelReservation: "取消预订",
    seatGuests: "入座点单",
    guestName: "客人姓名",
    guestCount: "人数",
    phone: "电话",
    reservationType: "预订类型",
    instantHold: "即时预留",
    scheduled: "预约时间",
    selectDate: "选择日期",
    selectTime: "选择时间",
    notes: "备注",
    cancelReason: "取消原因",
    customerCancelled: "客人取消",
    noShow: "未到店",
    otherReason: "其他",
    cancelNote: "备注",
    confirmCancel: "确认取消",
    actualGuestCount: "实际人数",
    searchMember: "输入手机号搜索会员",
    linkMember: "关联会员",
    skipMember: "跳过",
    seatAndOrder: "入座点单",
    reservationList: "预订列表",
    allReservations: "全部",
    pendingReservations: "待到",
    seatedReservations: "已入座",
    cancelledReservations: "已取消",
    noReservationsToday: "今日无预订",
    reservedAt: "预订时间",
    reservedFor: "预订人",
    guestNameRequired: "请输入客人姓名",
    reservationInfo: "预订信息",
    memberTier: "会员等级",
    noMemberFound: "未找到会员",

    // Menu management
    addCategory: "添加分类",
    editCategory: "编辑分类",
    deleteCategory: "删除分类",
    categoryName: "分类名称",
    systemCategory: "系统",
    uploadImage: "上传图片",
    imageUrl: "图片链接",
    removeImage: "移除",
    modifierGroups: "加料/配置组",
    addModifierGroup: "添加配置组",
    editModifierGroup: "编辑配置组",
    deleteModifierGroup: "删除配置组",
    optionName: "选项名称",
    optionPrice: "价格",
    addOption: "添加选项",
    editItem: "编辑菜品",
    itemDetails: "菜品详情",
    comboConfig: "套餐配置",
    // Recipe
    ingredients: "原料配方",
    addIngredient: "添加原料",
    selectIngredient: "选择原料",
    quantityPerServing: "每份用量",
    estimatedCost: "预估成本",
    linkedItems: "关联菜品",
    availablePortions: "可制作份数",
    projectedUsage: "预计用量",
    // Inventory intake
    receivingForm: "进货录入",
    scanInvoice: "扫描进货单",
    analyzing: "识别中...",
    addRow: "添加行",
    supplier: "供应商",
    totalCost: "总成本",
    submitReceiving: "提交进货",
    scanResult: "识别结果",
    confidence: "可信度",
    matchedItem: "匹配原料",
    reviewAndSubmit: "确认提交",
    noMatch: "未匹配",
    unitCost: "单价",
    // KDS
    kitchenDisplay: "厨房显示",
    kitchenView: "厨房",
    pickupView: "取餐",
    startPreparing: "开始制作",
    markReady: "完成",
    markServed: "已出餐",
    pickedUp: "已取餐",
    orderCancelled: "订单已取消",
    acknowledged: "已确认",
    kdsWarningMinutes: "警告阈值（分钟）",
    kdsUrgentMinutes: "紧急阈值（分钟）",
    kdsTimingSettings: "KDS 时间设置",
    kdsTimingDesc: "厨房工单颜色编码阈值",
    preparing: "制作中",
    readyForPickup: "等待取餐",
    newOrders: "新订单",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>("en");
  const t = useCallback((key: string) => dict[lang]?.[key] || dict.en[key] || key, [lang]);
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
};

export const useLanguage = () => useContext(LangContext);
